FROM ubuntu:20.04
## TODO WILL ADD IN MORE CONTENT
## WILL HAVE IT'S OWN IMAGE
## WILL OFFER A CONTAINERIZED VERSION AND SHELL SESSION TO TERRAFORM ENVIRONMNET
## WILL TEST TERAFORM PROVIDERS INSIDE THE CONTAINER
COPY . /app
RUN make /app
ENTRYPOINT ["/bin/bash"]
